src/app/(marketing)/layout.tsx, src/components/marketing/global/open-source/open-source-block.tsx, src/components/marketing/homepage/features/features-bento-grid.tsx, src/components/marketing/homepage/hero/hero.tsx, src/components/marketing/large-text.tsx
keyword targeting
landing page copy changes
=> SEO improvements

src/app/(dashboard)/(questions)/question/[uid]/page.tsx, src/app/(marketing)/[uid]/page.tsx, src/app/(no_nav)/(payment)/upgrade/page.tsx, src/components/dashboard/all-questions-bento-box.tsx, src/components/dashboard/dashboard-bento-grid.tsx, src/components/global/navigation/sidebar.tsx, src/components/leaderboard/fastest-times.tsx, src/components/marketing/global/navigation.tsx, src/components/payment/payment-card.tsx, src/components/questions/single/answer-question-modal.tsx, src/components/ui/alert-dialog.tsx, src/components/ui/feedback-button.tsx
addressing some issues I spotted whilst navigating the dashboard on mobile. Will need another round of checks before launch.
=> site wide mobile amends

package-lock.json, package.json, src/actions/questions/get-suggestions.ts, src/app/(dashboard)/(default_layout)/statistics/page.tsx, src/components/global/hero.tsx, src/components/questions/suggested-questions-table.tsx, src/components/statistics/suggested-questions.tsx
adding 'suggested questions' to the statistics page.
=> feat(stats): adding base suggested questions card to stats page

package-lock.json, package.json, src/utils/index.ts, src/utils/user.ts
filtering out profanity in display names
=> feat: adds bad-words filter to filter out bad words in usernames

.env.example, CONTRIBUTING.md, src/actions/ai/statistics/generate-report.ts, src/actions/ai/statistics/utils/generate-report-html.ts, src/utils/constants/prompts.ts
adding the creation of report html to the report.
=> feat(stats): start of report html generation

src/actions/ai/reports/generate-report.ts, src/actions/ai/reports/get-reports.ts, src/actions/user/authed/get-user.ts, src/app/(app)/(default_layout)/(roadmaps)/roadmaps/page.tsx, src/app/(app)/(default_layout)/statistics/reports/page.tsx, src/components/app/questions/question-card.tsx, src/components/app/roadmaps/[uid]/roadmaps-card.tsx, src/components/app/roadmaps/questions/[uid]/question-card.tsx, src/components/app/roadmaps/questions/question-card.tsx, src/components/app/statistics/stats-report-card-loading.tsx, src/components/app/statistics/stats-report-card.tsx, src/types/Stats.ts, src/utils/time.ts
adds the `/statistics/reports/` page to the app
=> creating user report page overview

src/actions/ai/reports/delete.ts, src/actions/ai/reports/generate-report.ts, src/app/(app)/(default_layout)/statistics/reports/page.tsx, src/components/app/questions/question-card.tsx, src/components/app/roadmaps/questions/[uid]/question-card-menu.tsx, src/components/app/statistics/generate-report-button.tsx, src/components/app/statistics/stats-report-card-menu.tsx, src/components/app/statistics/stats-report-card.tsx, src/components/ui/dropdown-menu.tsx
adding the ability to delete a single report via the report card dropdown menu on reports/overview
=> feat(stats): delete single report functionality added

prisma/migrations/20241231223050_adds_total_time_taken_to_report_schema/migration.sql, prisma/schema/statistics.prisma, src/actions/ai/reports/generate-report.ts, src/actions/statistics/get-stats-chart-data.ts, src/actions/statistics/reports/get-reports.ts, src/app/(app)/(default_layout)/layout.tsx, src/app/(app)/(default_layout)/statistics/page.tsx, src/components/app/onboarding/onboarding-context.tsx, src/components/app/statistics/generate-report-button.tsx, src/components/app/statistics/range-picker.tsx, src/components/app/statistics/statistics-overview-menu.tsx, src/components/app/statistics/statistics-report-content.tsx, src/components/app/statistics/statistics-report.tsx, src/components/app/statistics/stats-report-card-menu.tsx, src/components/app/statistics/total-question-chart.tsx
general hotfixes to the reports / stats feature on the app.
=> fix(reports): disable generate report btn if free user

.prettierignore, src/app/(marketing)/blog/[slug]/page.tsx, src/app/(marketing)/blog/posts/how-to-become-software-engineer-2025.mdx, src/components/mdx/mdx-heading.tsx, src/components/mdx/mdx-list.tsx, src/mdx-components.tsx
New blog post for becoming a software engineer in 2025.
=> marketing: new blog post - become a SWE in 2025.

CONTRIBUTING.md
=> docs: fix clone url

next.config.js, src/app/(app)/dashboard/page.tsx, src/app/(app)/settings/profile/page.tsx, src/components/app/leaderboard/fastest-times.tsx, src/components/app/leaderboard/leaderboard-longest-streaks.tsx, src/components/app/leaderboard/leaderboard-most-questions-answered.tsx, src/components/app/leaderboard/leaderboard-today-board.tsx, src/components/app/onboarding/onboarding-step-one.tsx, src/components/global/navigation/sidebar-footer.tsx, src/components/ui/profile-picture.tsx, src/lib/zod/schemas/user-details-schema.ts
adding profile picture uploading too:
- onboarding
- settings
adding in profile picture to:
- sidebar footer
- leaderboards
=> User bug/look into user profile picture uploading

src/app/(marketing)/features/statistics/page.tsx, src/components/app/statistics/total-question-chart.tsx, src/components/marketing/features/roadmap/roadmap-hero.tsx, src/components/marketing/features/roadmap/roadmap-three-grid.tsx, src/components/marketing/features/statistics/skewed-question-cards.tsx, src/components/marketing/features/statistics/stats-hero.tsx, src/components/marketing/features/statistics/stats-report-section.tsx, src/components/marketing/global/footer/footer.tsx, src/components/marketing/global/navigation/navigation-items.tsx, src/components/marketing/homepage/features/features-bento-grid.tsx, src/components/marketing/homepage/hero/hero.tsx, src/utils/index.ts
adding the statistics page to the marketing site.
=> feat(marketing): start of features/statistics marketing page

src/actions/questions/get-next-question.ts, src/actions/roadmap/delete-roadmap.ts, src/actions/roadmap/fetch-single-roadmap.ts, src/actions/roadmap/questions/fetch-roadmap-question.ts, src/actions/roadmap/update-roadmap-details.ts, src/actions/statistics/reports/delete.ts, src/actions/statistics/reports/get-report.ts, src/app/(app)/(default_layout)/statistics/page.tsx, src/app/(app)/(default_layout)/statistics/reports/[uid]/page.tsx, src/app/(app)/(questions)/question/[uid]/layout.tsx, src/app/(app)/(questions)/question/[uid]/page.tsx, src/app/(app)/(roadmap)/roadmap/[roadmapUid]/(roadmapUid)/page.tsx, src/app/(app)/(roadmap)/roadmap/[roadmapUid]/[uid]/page.tsx, src/app/(app)/layout.tsx, src/components/app/roadmaps/[uid]/dropdown.tsx, src/components/app/roadmaps/[uid]/edit-roadmap-modal.tsx, src/components/auth/login.tsx, src/hooks/use-user-server.ts, src/middleware.ts
if a non authed users tried to go to a route, we redirect them back to that route upon login
=> feat(app): more secure actions, redirecturl added + middleware updated

src/app/(app)/(default_layout)/(questions)/questions/custom/page.tsx, src/app/(app)/(default_layout)/(questions)/questions/page.tsx, src/app/(app)/(default_layout)/(questions)/questions/previous/page.tsx, src/components/global/filters/chips.tsx, src/components/global/filters/filter.tsx, src/components/global/filters/filters-wrapper.tsx, src/components/global/filters/search/tag-search.tsx, src/components/global/filters/tags-carousel-container.tsx, src/components/global/filters/tags-carousel.tsx, src/hooks/use-user.ts
allowing users to filter the tag carousel via a search input.
=> feat(filters): tag search filtering added.

src/actions/questions/get-onboarding.ts, src/app/(no_nav)/onboarding/page.tsx, src/components/app/onboarding/onboarding-context.tsx, src/components/app/onboarding/onboarding-form.tsx, src/components/app/onboarding/onboarding-step-one.tsx, src/components/app/onboarding/onboarding-step-three.tsx, src/components/app/onboarding/onboarding-step-two.tsx, src/components/global/navigation/sidebar-footer.tsx
generating questions for the user within 30 seconds of signing up! nice
=> feat(onboarding): new onboarding flow

package-lock.json, package.json, src/actions/ai/roadmap/utils/generate-roadmap.ts, src/utils/constants/prompts.ts
using claude to generate questions. More interesting questions are produced via claude.
=> feat(roadmaps): using claude to generate questions

src/actions/leaderboard/get-most-questions-answered.ts, src/app/(app)/(default_layout)/(roadmaps)/roadmaps/page.tsx, src/app/(app)/(roadmap)/loading.tsx, src/app/(app)/(roadmap)/roadmap/[roadmapUid]/(roadmapUid)/loading.tsx, src/app/(app)/(roadmap)/roadmap/[roadmapUid]/(roadmapUid)/page.tsx, src/app/(app)/(roadmap)/roadmap/[roadmapUid]/[uid]/layout.tsx, src/app/(app)/(roadmap)/roadmap/[roadmapUid]/[uid]/loading.tsx, src/app/(app)/(roadmap)/roadmap/[roadmapUid]/[uid]/page.tsx, src/components/app/leaderboard/leaderboard-most-questions-answered.tsx, src/components/app/roadmaps/[uid]/roadmaps-card-loading.tsx, src/components/app/roadmaps/[uid]/roadmaps-card.tsx, src/components/app/roadmaps/questions/question-card.tsx, src/components/app/roadmaps/questions/roadmap-answer-form.tsx, src/components/global/hero.tsx, src/components/marketing/pricing/pricing-card.tsx
UX improvements for the roadmap aspect of the app 🪄
=> fix(roadmaps): improving roadmap speeds

package-lock.json, prisma/migrations/20250116214734_adds_difficulty_to_answer/migration.sql, prisma/schema/questions.prisma, src/actions/ai/questions/answer-help.ts, src/actions/answers/answer.ts, src/app/(app)/(questions)/question/[slug]/layout.tsx, src/app/(app)/(questions)/question/[slug]/page.tsx, src/app/(app)/(questions)/question/custom/[uid]/layout.tsx, src/app/(app)/(questions)/question/custom/[uid]/page.tsx, src/app/globals.css, src/components/app/questions/resources/question-tabs.tsx, src/components/app/questions/single/answer-question-form.tsx, src/components/app/questions/single/layout/code-display-wrapper.tsx, src/components/app/questions/single/layout/question-card.tsx, src/components/app/questions/single/layout/question-single-context.tsx, src/components/app/questions/single/layout/question-submitted.tsx, src/lib/zod/schemas/ai/answer-help.ts, src/types/Answers.ts, src/types/Questions.ts, src/utils/constants/prompts.ts, src/utils/data/leaderboard/get-fastest.ts
improvement the design & flow of the question submission flow:
- remove modal
- give user feedback on submission (needs migration to add these to existing questions)
- related questions to be shown to user
- random question suggestion
- start implementing question point system? also needs a migration
=> feat(questions): start of context cleanup & improving submission flow

next.config.js, src/app/(marketing)/features/daily-coding-challenges/page.tsx, src/app/(marketing)/features/leaderboard/page.tsx, src/app/(marketing)/page.tsx, src/app/sitemap.ts, src/components/app/leaderboard/leaderboard-hero.tsx, src/components/marketing/features/leaderboard/leaderboard-features-left.tsx, src/components/marketing/features/leaderboard/leaderboard-features-right.tsx, src/components/marketing/features/leaderboard/leaderboard-features.tsx, src/components/marketing/features/leaderboard/leaderboard-hero.tsx, src/components/marketing/features/leaderboard/leaderboard-podium-showcase.tsx, src/components/marketing/features/roadmap/roadmap-hero.tsx, src/components/marketing/global/blocks/call-to-action-block.tsx, src/components/marketing/global/blocks/content-grid.tsx, src/components/marketing/global/footer/footer.tsx, src/components/marketing/global/navigation/mobile-menu.tsx, src/components/marketing/global/navigation/navigation-items.tsx, src/components/marketing/global/waitlist-form.tsx, src/components/ui/profile-picture.tsx
creating the `/features/leaderboard` page on the marketing site
=> marketing page - /features/leaderboard

src/app/(app)/(questions)/question/[slug]/layout.tsx, src/app/(app)/(questions)/question/[slug]/page.tsx, src/app/(app)/(questions)/question/custom/[uid]/layout.tsx, src/app/(app)/providers.tsx, src/components/app/code-editor/description-tab.tsx, src/components/app/code-editor/editor.tsx, src/components/app/questions/question-hint-trigger.tsx, src/components/app/questions/resources/question-tabs.tsx, src/components/app/questions/single/bookmark.tsx, src/components/app/questions/single/layout/question-single-context.tsx, src/components/app/questions/single/question-hint.tsx, src/components/global/navigation/question-navigation.tsx, src/utils/data/questions/question-navigation.ts
…text & sorting out code editor bg color
=> adding next & prev question navigation 

src/actions/answers/answer-onboarding.ts, src/app/(marketing)/page.tsx, src/components/app/onboarding/onboarding-footer.tsx, src/components/app/onboarding/onboarding-form.tsx, src/components/app/onboarding/onboarding-initial-questions.tsx, src/components/app/onboarding/onboarding-time-commitment.tsx, src/components/app/onboarding/onboarding-user-details.tsx, src/contexts/onboarding-context.tsx, src/hooks/use-onboarding-steps.ts
=> feat(onboarding): adding initial questions to onboarding flow
